config/routes.rb
Rails.application.routes.draw do
  
  resources :requests

end

app/models/request.rb
class Request < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true

  DEPARTMENT_SALES     = "Sales"
  DEPARTMENT_TECHNICAL = "Technical"
  DEPARTMENT_MARKETING = "Marketing"

  DEPARTMENTS = [DEPARTMENT_SALES, DEPARTMENT_TECHNICAL, DEPARTMENT_MARKETING]

  after_initialize :set_defaults

  def self.search(term)
    if term
      where(["LOWER(name) LIKE :search_term OR LOWER(email) LIKE :search_term
               OR LOWER(message) LIKE :search_term", {search_term: "%#{term}%"}])
    else
      all
    end
  end

  private

  def set_defaults
    self.done ||= false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def new
    @request = Request.new
  end

  def create
    request_params = params.require(:request).
                        permit([:name, :email, :department, :message])
    @request = Request.new request_params
    if @request.save
      redirect_to request_path(@request)
    else
      render :new
    end
  end

  def show
    @request = Request.find params[:id]
  end

  def edit
    @request = Request.find params[:id]
  end

  def update
    @request = Request.find params[:id]
    request_params = params.require(:request).
                      permit(:name, :email, :department, :message, :done)
    if @request.update request_params
      if request_params.has_key?(:done)
        redirect_to requests_path
      else
        redirect_to request_path(@request)
      end
    else
      render :edit
    end
  end

  def destroy
    @request = Request.find params[:id]
    @request.destroy
    redirect_to requests_path
  end

  def index
    @query    = params[:query]
    @requests = Request.order("done ASC").page(params[:page]).per(5).search(params[:query])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Supporter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/requests/edit.html.erb
<h1>Edit Support Request</h1>
<%= @request.errors.full_messages.join(", ") %>
<%= form_for @request do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :department %>
    <%= f.radio_button :department, Request::DEPARTMENT_SALES %>
    <%= f.label "department_sales", Request::DEPARTMENT_SALES %>
    <%= f.radio_button :department, Request::DEPARTMENT_MARKETING %>
    <%= f.label "department_marketing", Request::DEPARTMENT_MARKETING %>
    <%= f.radio_button :department, Request::DEPARTMENT_TECHNICAL %>
    <%= f.label "department_technical", Request::DEPARTMENT_TECHNICAL %>
  </div>
  <div>
    <%= f.label :message %>
    <%= f.text_area :message %>
  </div>
  <%= f.submit "Submit" %>
<% end %>

app/views/requests/index.html.erb
<%= form_tag requests_path, method: :get do %>
  <%= text_field_tag :query, @query %>
  <%= submit_tag "Search" %>
<% end %>
<h1>All Requests</h1>
<% @requests.each do |request| %>
  <div>
    <%= link_to request.name, request_path(request) %>
    <% if request.done %>
      <%= form_for request do |f| %>
        <%= f.hidden_field :done, value: false %>
        <%= f.submit "Mark UnDone" %>
      <% end %>
    <% else %>
      <%= form_for request do |f| %>
        <%= f.hidden_field :done, value: true %>
        <%= f.submit "Mark Done" %>
      <% end %>
    <% end %>
    <%#= link_to "#{request.done}", request_path(request), method: :patch %>
  </div>
<% end %>

<%= paginate @requests %>

app/views/requests/new.html.erb
<h1>New Support Request</h1>
<%= @request.errors.full_messages.join(", ") %>
<%= form_for @request do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :department %>
    <%= f.radio_button :department, Request::DEPARTMENT_SALES %>
    <%= f.label "department_sales", Request::DEPARTMENT_SALES %>
    <%= f.radio_button :department, Request::DEPARTMENT_MARKETING %>
    <%= f.label "department_marketing", Request::DEPARTMENT_MARKETING %>
    <%= f.radio_button :department, Request::DEPARTMENT_TECHNICAL %>
    <%= f.label "department_technical", Request::DEPARTMENT_TECHNICAL %>
  </div>
  <div>
    <%= f.label :message %>
    <%= f.text_area :message %>
  </div>
  <%= f.submit "Submit" %>
<% end %>

app/views/requests/show.html.erb
<h1><%= @request.name %></h1>
<p>Email: <%= mail_to @request.email %></p>
<p>Department: <%= @request.department %></p>
<p>Message: <%= @request.message %></p>
<hr>
<%= link_to "Edit Request", edit_request_path(@request) %>
<%= link_to "Delete", request_path(@request), method: :delete,
              data: {confirm: "Are you sure?" } %>